name: tappyshape
description: A modern Flutter game where players tap shapes before they disappear.
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  audioplayers: ^5.2.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.3.10
  integration_test:
    sdk: flutter

flutter_native_splash:
  color: "#000000"
  image: assets/images/TouchIt ICON.Png
  android: true
  ios: true
  web: true
  android_12:
    image: assets/images/TouchIt ICON.Png
    icon_background_color: "#000000"
  ios_content_mode: center
  fullscreen: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/TouchIt ICON.Png"
  min_sdk_android: 21
  remove_alpha_ios: true
  macos:
    generate: true
    image_path: "assets/images/TouchIt ICON.Png"
  windows:
    generate: true
    image_path: "assets/images/TouchIt ICON.Png"
  web:
    generate: true
    image_path: "assets/images/TouchIt ICON.Png"

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/sounds/
    - assets/sounds/GoodTap1_effect.mp3
    - assets/sounds/GoodTap2_effect.mp3
    - assets/sounds/BadTap_effect.mp3
    - assets/sounds/GameOver_effect.mp3
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700 